#!/bin/sh

uci set network.lte=interface
uci set network.lte.proto='qmi'
uci set network.lte.device='/dev/cdc-wdm0'
uci set network.lte.apn='internet'
uci set network.lte.auto='1'

uci commit network
/etc/init.d/network reload
