#!/bin/sh /etc/rc.common
# Modem Control Script untuk Fibocom L716

START=95
STOP=10

start() {
    logger -t modemctl "Memulai modem semutcriminals"
    uqmi -d /dev/cdc-wdm0 --set-client-id wds 0
    uqmi -d /dev/cdc-wdm0 --start-network internet --autoconnect
}

stop() {
    logger -t modemctl "Memutus koneksi modem semutcriminals"
    uqmi -d /dev/cdc-wdm0 --stop-network 0 --autoconnect
}
