name: Build OpenWrt TL-MR6400 + L716

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc rsync wget unzip python3 python3-distutils python3-setuptools python3-pip
          git config --global user.email "semut1287@gmail.com"
          git config --global user.name "semut2019"

      - name: Clone OpenWrt source
        run: |
          git clone https://github.com/openwrt/openwrt.git openwrt
          cd openwrt
          git checkout v23.05.3  # atau commit tag yang diinginkan
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy config and files
        run: |
          cp -r config openwrt/.config
          cp -r files openwrt/files
          [ -d patches ] && cp -r patches openwrt/ || true

      - name: Build firmware
        run: |
          cd openwrt
          make defconfig
          make -j$(nproc)

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware
          path: openwrt/bin/targets/
